version: "3.1"

services:
  wordpress:
    image: wordpress
    restart: always
    ports:
      - 8080:80
    environment:
      WORDPRESS_DB_HOST: localhost
      WORDPRESS_DB_USER: docuser
      WORDPRESS_DB_PASSWORD: docpass
      WORDPRESS_DB_NAME: docdb
    volumes:
      - wordpress:/var/www/html
      - ./sage:/var/www/html/wp-content/themes/sage/
  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: docdb
      MYSQL_USER: docuser
      MYSQL_PASSWORD: docpass
      MYSQL_RANDOM_ROOT_PASSWORD: "1"
    volumes:
      - db:/var/lib/mysql

volumes:
  wordpress:
  db:
